version: '1.3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable_freqai
    restart: unless-stopped
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    command: >
      trade
      --config /freqtrade/user_data/config.json
      --strategy FreqAI_RSIHunter
      --freqaimodel LightGBMClassifier
      --dry-run
